### ISSUE TITLE
Menus are not supporting locale and thus not translated if multilingual app

### ISSUE THREAD

**Issue by joshirohit100** [acquia/next-acms#115]
Steps -

- Setup multilingual drupal site
- Setup nextjs app with 2 locales
- Update / add menu in drupal for different languages
- Notice the next app on FE - Menus are showing in english only and not in the language / locale of the app

This is happening because -
`drupal.getMenu()` of the next-drupal, expects locale to be passed as an argument and not relies or uses context like other methods (ex - getResourceCollectionFromContext())

So - `getMenus()` of `lib/get-menus.ts` - we need to pass context as an argument from caller and to this getMenu() and then need to pass the locale

**Comment by joshirohit100** [comment]
Quick one https://github.com/acquia/next-acms/pull/116

**Comment by lauriii** [comment]
https://github.com/acquia/next-acms/pull/116 has been merged.
