### ISSUE TITLE
Convert repository to a monorepo

### ISSUE THREAD

**Issue by lauriii** [acquia/next-acms#16]
This package currently ships single package which is a Next.js template. On top of the Next.js template we want to serve a library that is added as a dependency in the Next.js template, so that we can ship updates in the future.

### Proposed solution

1. Convert repository to a monorepo that contains two packages; _next-acms_ and _next-acms-basic-starter_.
2. Publish both packages in npm.
3. Update commands in the README to match the new process.

**Comment by fiasco** [comment]
What are examples of updates we might want to ship? This seems counter to what we initially set out to provide: a starter kit. While a starter kit is a starting point that you customize from, shipping a library makes projects dependent on it, its bugs, limitations and security flaws. This was why we wanted just a starter kit.

**Comment by lauriii** [comment]
> What are examples of updates we might want to ship?

An example of this might be if we need to provide Acquia specific developer tooling. For example, we moved the manual revalidation logic to `next-acms` so that it's possible to make it compatible with `acquia_purge` in future. Other examples could be tooling to integrate with Acquia Search.

I believe that the focus should be on the starter kit, even if we provide a package that provides some tooling to improve the developer experience.

**Comment by lauriii** [comment]
Closing this since the repository has been converted into a monorepo. Feel free to open follow-up issues if there's any additional discussion that should take place. 👍
