### ISSUE TITLE
Document ACMS drupal install

### ISSUE THREAD

**Issue by harumijang** [acquia/next-acms#18]

**Comment by harumijang** [comment]
Have PHP 7.4 installed (ACMS doesn't work with PHP 8.1)

1. Run `composer create-project acquia/drupal-recommended-project acms-demo`

2. Inside of acms-demo directory run `composer config repositories.acquia_cms_starterkit vcs 'git@github.com:acquia/acquia-cms-starterkit.git'`

3. After the composer repository is added, run the below composer command to download the tool:
`composer require acquia/acquia-cms-starterkit:dev-develop`

4. Run the following command to to set up site:
` ./vendor/bin/acms acms:install`

5. Go into `usr/local/etc/httpd/extra/httpd-vhosts.conf` and add a virtual host 
```
## Example
<VirtualHost *:80>
    DocumentRoot "/Users/myname/acms-demo/docroot"
    ServerName acms-demo.test
    ErrorLog "/var/log/apache2/error.log"
</VirtualHost>
```
6. Set up permissions in `usr/local/etc/httpd/httpd.conf`
```
## Example
<Directory "/Users/harumi.jang/acms-demo">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks

    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   AllowOverride FileInfo AuthConfig Limit
    #
    AllowOverride All

    #
    # Controls who can get stuff from this server.
    #
    Require all granted
</Directory>
```
7. Restart apache server `sudo apachectl restart` and your Drupal site should now be running

**Comment by lauriii** [comment]
Thank you for documenting the steps it took you to install `next-acms-basic-starter`. The documentation has been moved to dev.acquia.com and all the necessary steps will be documented there. We are updating our README to point to the dev.acquia.com documentation on https://github.com/acquia/next-acms/pull/41.

**Comment by phenaproxima** [comment]
The instructions worked for me as well.
