### ISSUE TITLE
Get image metadata to power next.js image processing

### ISSUE THREAD

**Issue by fiasco** [acquia/next-acms#38]
Next.js has the ability to size its own images which is quite a powerful capability and gives a lot of autonomy to the node developer. However, its capability is limited when it doesn't know the image height and width which it needs to derive from Drupal (assuming Drupal is providing the image).

We should add support to the Image Media component pull this metadata so the node developer can size the image to application specifications.

### Acceptance criteria

Width and height info on the source image.
Bonus points available if data is also on image styles... buts not necessary (and probably unknown in most cases).

**Comment by lauriii** [comment]
We added support for sizes attributes including examples of how to use it in https://github.com/acquia/next-acms/pull/75. Rest of this would be covered by https://github.com/acquia/next-acms/issues/37 and https://github.com/acquia/next-acms/issues/71. Please let me know if there's anything that isn't covered by these two issues so we can re-open this.
