### ISSUE TITLE
Handle exceptions caused by empty menus

### ISSUE THREAD

**Issue by lauriii** [acquia/next-acms#4]
At the moment, there's an uncaught exception when main or footer menu is empty (meaning 0 enabled links). This could be potentially mostly a DX problem since when you create your site, you would start from an empty menu. However, I don't think it makes sense to prevent the page from rendering the menu is empty, therefore we should probably just catch the exception in this case.

How do we differentiate between empty menus and actual issue with permissions? Maybe we can't, and have to catch the exception for all 403 requests for now and reference https://www.drupal.org/project/jsonapi_menu_items/issues/3213317

<img width="971" alt="Screen Shot 2022-03-17 at 8 55 49" src="https://user-images.githubusercontent.com/1845495/158753773-ba06d575-4ff8-47f7-aeb6-1bc6d75527d7.png">

**Comment by shadcn** [comment]
The patch from the linked issue fixes this. [I tested and marked the issue as RTBC](https://www.drupal.org/project/jsonapi_menu_items/issues/3213317#comment-14453894).

I've also pushed a fix on the next side to handle empty menu items. See https://github.com/chapter-three/next-drupal/pull/127

**Comment by shadcn** [comment]
The patch was applied and marked as fixed on d.o: https://www.drupal.org/project/jsonapi_menu_items/issues/3213317#comment-14459106

I'll tag a new patch release for next-drupal

**Comment by shadcn** [comment]
@lauriii I just tagged `next-drupal 1.2.1` with the fix. https://github.com/chapter-three/next-drupal/milestone/4?closed=1

Note: we'll need the dev release for jsonapi_menu_items module (for now)

**Comment by lauriii** [comment]
A new release of jsonapi_menu_items was tagged today https://www.drupal.org/project/jsonapi_menu_items/releases/1.2.3 meaning that finally we should be able to fully address this 🎉

**Comment by lauriii** [comment]
Confirmed that with the latest version of _jsonapi_menu_items_, this has been addressed.
