### ISSUE TITLE
Server Error : Failed to fetch JSON:API index at https://example.com/jsonapi - fetch failed

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/next-acms#51]
## Background

-  I am trying to setup new ACMS v2 Headless bundle on local.
-  I am able to setup Drupal Application - Site is working fine.
-  I am able to setup Nextjs Application - Unable to access the site or Able to access `http://localhost:3000/` with Server Error

## Steps to Reproduce
1. Setup ACMS Headless Site Successfully [Check More details section]
2. Enable the Nextjs and Headless mode via Tour-> Getting Started
3. Copy the Environment Variables and Store it.
4. Setup Nextjs APP [Check More details section]
5. cp .env.example .env.local
6. Paste the credentials/Environment details into `.env.local` file
7. Run the `npm run dev` command
8. Access the url **http://localhost:3000/**

**Error Message on the terminal**
```
MacBookPro-JayakrishnanJayabal :: ~/works/acms-nextjs ‹main*› » npm run dev                                                                        130 ↵

> next-acms-basic-starter@1.0.0 dev
> NODE_OPTIONS='--inspect' next dev

Debugger listening on ws://127.0.0.1:9229/e2f4bcd8-a39f-4cb9-aea5-600882e06c9f
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/jayakrishnan.jayabal/works/acms-nextjs/.env.local
wait  - compiling...
event - compiled client and server successfully in 323 ms (126 modules)
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 245 ms (211 modules)
(node:39159) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 57 ms (212 modules)
error - Error: Failed to fetch JSON:API index at https://acms-headless.lndo.site/jsonapi - fetch failed
```

Error message on the UI
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/19162800/177574478-aeaaddc1-4b50-4126-8877-d711fb439572.png">

### Setup ACMS Headless Successfully site using ###
`composer create-project --no-interaction acquia/drupal-recommended-project acms-headless`
Added lando configuration to have the local setup

 ```
APPSERVER URLS  https://localhost:49154
                 http://localhost:49155
                 http://acms-headless.lndo.site/
                 https://acms-headless.lndo.site/
```
Executed `./vendor/bin/acms acms:install`

```
Please choose bundle from one of the above use case [acquia_cms_enterprise_low_code]:
 > acquia_cms_headless

 Do you want to enable demo content (yes/no) ? [no]:
 > yes

 Please provide the Google Maps API Key:
 >
 The Google Maps API key is not set. So, you might see errors, during enable modules step. They are technically harmless, but the maps will not work.
 You can set the key later from: /admin/tour/dashboard and resave your starter content to generate them.

Seems Drupal is already downloaded. The downloaded Drupal core version is: 9.4.1. Skipping downloading Drupal.
```

### Setup nextjs app

```
npx create-next-app -e https://github.com/acquia/next-acms/tree/main/starters/basic-starter
✔ What is your project named? … acms-nextjs
Creating a new Next.js app in /Users/jayakrishnan.jayabal/works/acms-nextjs.

Downloading files from repo https://github.com/acquia/next-acms/tree/main/starters/basic-starter. This might take a moment.

Installing packages. This might take a couple of minutes.

yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 31.14s.

Initialized a git repository.

Success! Created acms-nextjs at /Users/jayakrishnan.jayabal/works/acms-nextjs
Inside that directory, you can run several commands:

  yarn dev
    Starts the development server.

  yarn build
    Builds the app for production.

  yarn start
    Runs the built app in production mode.

We suggest that you begin by typing:

  cd acms-nextjs
  yarn dev

```

**Comment by lauriii** [comment]
One known bug has been that the app renders an error if the site doesn't have menu items in main menu and footer. This was due to a bug in json_menu_items module. They made [a new release today](https://www.drupal.org/project/jsonapi_menu_items/releases/1.2.3) where that bug is fixed, meaning that I believe we should be able to fully address this now.

**Comment by lauriii** [comment]
The related bug https://github.com/acquia/next-acms/issues/4

**Comment by jayakrishnanj** [comment]
It is working now, Repeated the Steps and built new application. Able to access the Drupal Site and Nextjs Application.
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/19162800/177721696-c5f8827f-c0f1-46af-8fa0-35ed7ed35a04.png">

We can close this ticket now.

**Comment by joshirohit100** [comment]
I am still facing this issue
I have tried with lando for drupal install

error I am getting during the build - 
```
[next-drupal][error]: Error: Failed to fetch JSON:API index at https://acms-v2.lndo.site/jsonapi - fetch failed
    at /Users/rohit.joshi/projects/my_app/node_modules/next-drupal/dist/index.js:1998:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStaticProps (/Users/rohit.joshi/projects/my_app/.next/server/pages/places.js:93:20)
    at async renderToHTML (/Users/rohit.joshi/projects/my_app/node_modules/next/dist/server/render.js:451:20)
    at async /Users/rohit.joshi/projects/my_app/node_modules/next/dist/export/worker.js:251:36
    at async Span.traceAsyncFn (/Users/rohit.joshi/projects/my_app/node_modules/next/dist/trace/trace.js:79:20)
```

**Comment by joshirohit100** [comment]
This is now working for me.

Issue was - in `.env.local` file, in `NEXT_PUBLIC_DRUPAL_BASE_URL` variable, https was used. I changed this to `http` and this worked.

It seems on local (lando setup), drupal url for this generated with https while actual was with only `http`.

For others - Just check once drupal setup is done for headless -
try below with both `https` and `http` and see which will work and then update/use the variable accrodingly
```
curl -X GET SITEURL
```

**Comment by lauriii** [comment]
Opened https://github.com/acquia/next-acms/issues/62 for improving the experience of debugging this.
