### ISSUE TITLE
next-acms breaks when no default content is added

### ISSUE THREAD

**Issue by harumijang** [acquia/next-acms#57]
next-acms should work with the ACMS headless starter when no default content is added. 
Related issue #4

**Comment by harumijang** [comment]
Added error handling in this PR: https://github.com/acquia/next-acms/pull/58

**Comment by lauriii** [comment]
I can't reproduce this with the default content model even if I don't h any content, including menu links. I can only reproduce this if I also disable the default content model. I think that's sort of a separate problem and I don't know how much we want to accommodate for that use case. Folks who decide to install ACMS without the default content model would have to either update our basic-starter to work with their content model or start from _next-drupal_ basic-starter.

I'm wondering if this is something we should handle by documentation 🤔

**Comment by lauriii** [comment]
This could be improved by https://github.com/acquia/next-acms/issues/62

**Comment by lauriii** [comment]
We are now checking for missing content types in the pre-flight check. This results in a human readable error message that guides users in the case where Acquia CMS has been installed without the default content model. Installing the default content model without default content is working.
