### ISSUE TITLE
Improve DX for scenarios where Next.js and Drupal integration is not working correctly

### ISSUE THREAD

**Issue by lauriii** [acquia/next-acms#62]
There are multiple different ways how the Next.js and Drupal integration won't work correctly. This includes (but not limited to):

1. ACMS installed without default content model
2. Content model has been modified
3. Incompatible web server setup (e.g. web server not compatible with JSON:API)
4. Incorrect env variables generated by the backend

## Proposed solution
Do a "preflight check" which ensures that fundamental aspects of the integration are working as expected. Fail early in case it is determined that the integration with the backend is not working as required by the Next.js app. Provide helpful error messages with links to documentation that documents how most common failures can be debugged.

The "preflight check" could check that the content model includes all content types from `CONTENT_TYPES` in `[...slug].tsx`. This would happen by checking `/jsonapi` which would also work as a test for ensuring that the API from the backend can be reached.

**Comment by harumijang** [comment]
# Common failures with Next.js and Drupal integration
## Content mismatch
In the case of a content mismatch, there are two options to fix this:
1. Reinstall Acquia CMS with both the content model and demo content enabled to ensure that the backend has all the content that the Next.js site uses.
2. Check if all the items in `CONTENT_TYPES` in `[...slug].tsx` exist in the ACMS backend and if not either add the missing content types to the CMS or edit the list of  `CONTENT_TYPES` to match what is in ACMS.

## Incompatible web server setup
Check if you are able to make a request to `/jsonapi` on ACMS. If you are getting a valid response but your Next.js site isn't working,  your web server might not be compatible with JSON:API. If you are using valet as your web server, please see https://github.com/laravel/valet/issues/771#issuecomment-485533478 for the known solution.

## Incorrect env variables generated by the backend
[i'm not sure of the solution would it just be to reinstall ACMS?]

**Comment by lauriii** [comment]
Added this to https://github.com/acquia/next-acms/wiki/Debugging-common-errors-with-Next.js-and-Drupal-integration

**Comment by lauriii** [comment]
The API for executing these checks have been added: https://github.com/acquia/next-acms/pull/65.

Next step on this is to write some unit tests for the new API which was splitted to another PR since we still need to setup Jest. After that, we can make a new release of `next-acms` and update basic-starter to use it.
