### ISSUE TITLE
Add documentation for how security issues should be reported

### ISSUE THREAD

**Issue by lauriii** [acquia/next-acms#64]
We should add documentation for instruction on how security vulnerabilities can be disclosed responsibly. We should also document our policy for handling security issues.

**Comment by lauriii** [comment]
We could potentially include text from https://www.acquia.com/why-acquia/industries/security:

> Reporting a Security Issue
> At Acquia we take the security of our products very seriously. We educate our staff on security best practices and our development process includes quality assurance steps to ensure our products are of high quality and secure. However, like all complex software products, it is possible that a security vulnerability may be present in one of our products. If you discover a security issue or vulnerability in an Acquia product or service, we ask that you report this to us confidentially.
> 
> Please email the details to our security team at security@acquia.com. We appreciate responsible disclosure and will acknowledge security researchers when an issue has been reported, adhering to the following parameters.
> 
> Acquia does not currently have a bug bounty program in place, however we are happy to credit researchers with their name and a link to an address of their choosing (e.g. Twitter or personal website) on our Hall of Fame below.

I think this could be potentially simplified to just:

> Reporting a Security Issue
> If you believe you have found a security vulnerability in an Acquia product or service, we encourage you to responsibly disclose this and not open a public issue. We will investigate all legitimate reports. Please email the details to our security team at security@acquia.com.

We could also add a link to https://www.acquia.com/why-acquia/industries/security for more information.

**Comment by mcdruid** [comment]
As discussed with @lauriii in chat, the Acquia SecOps team is happy to triage reports sent to security@acquia.com in the absence of a better system e.g. private security issues within github.

The public Security page(s) linked to above are currently the best ones to link to. There is also Acquia's [security.txt](https://www.acquia.com/.well-known/security.txt) which we could reference from this project if that's helpful, but that links to the same things ultimately.
